#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

postgres_ready() {
python << END
import sys
import os
import psycopg2

try:
    conn = psycopg2.connect(
        dbname=os.environ.get("SQL_DATABASE", "hello_django"),
        user=os.environ.get("SQL_USER", "user"),
        password=os.environ.get("SQL_PASSWORD", "password"),
        host=os.environ.get("SQL_HOST", "localhost"),
        port=os.environ.get("SQL_PORT", "5432")
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"